# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_vpc_peering_connection.pcx-0659fe288fc855311
  id = "pcx-0659fe288fc855311"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593
  id = "TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1
  id = "TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}
