# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_iam_policy.lambda_function_StreamConsumer1_st_dynamodb-tour1
  id = "arn:aws:iam::952133486861:policy/lambda_function_StreamConsumer1_st_dynamodb-tour1"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-AlarmHigh-9e9f0e53-6b5f-4e7b-874f-0490a9077040
  id = "TargetTracking-table/Metrics-Autoscaling1-AlarmHigh-9e9f0e53-6b5f-4e7b-874f-0490a9077040"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-AlarmHigh-a49f146b-3c4b-4ac8-b5bf-0cc56c0c836c
  id = "TargetTracking-table/Metrics-Autoscaling1-AlarmHigh-a49f146b-3c4b-4ac8-b5bf-0cc56c0c836c"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-AlarmLow-052436bf-aef0-43c5-9083-7313d19b467d
  id = "TargetTracking-table/Metrics-Autoscaling1-AlarmLow-052436bf-aef0-43c5-9083-7313d19b467d"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-AlarmLow-62e89601-066f-4ec7-89ff-8534d7dc1f5d
  id = "TargetTracking-table/Metrics-Autoscaling1-AlarmLow-62e89601-066f-4ec7-89ff-8534d7dc1f5d"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-ProvisionedCapacityHigh-00be6923-8f09-428c-b4f6-84b4fbec7f65
  id = "TargetTracking-table/Metrics-Autoscaling1-ProvisionedCapacityHigh-00be6923-8f09-428c-b4f6-84b4fbec7f65"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-ProvisionedCapacityHigh-b16e6fdd-0f6b-4f16-b7f0-0b46e9a629df
  id = "TargetTracking-table/Metrics-Autoscaling1-ProvisionedCapacityHigh-b16e6fdd-0f6b-4f16-b7f0-0b46e9a629df"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-ProvisionedCapacityLow-292e8b64-aa19-4c19-b77a-9e4fb2bec3d3
  id = "TargetTracking-table/Metrics-Autoscaling1-ProvisionedCapacityLow-292e8b64-aa19-4c19-b77a-9e4fb2bec3d3"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Metrics-Autoscaling1-ProvisionedCapacityLow-7086d8ee-9eb2-41c5-8586-7eec806bf04d
  id = "TargetTracking-table/Metrics-Autoscaling1-ProvisionedCapacityLow-7086d8ee-9eb2-41c5-8586-7eec806bf04d"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-AlarmHigh-8f44b28b-b600-4db9-9a30-48798b633c23
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-AlarmHigh-8f44b28b-b600-4db9-9a30-48798b633c23"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-AlarmHigh-eebd7cf5-f1df-457c-b9ae-8527f86c46eb
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-AlarmHigh-eebd7cf5-f1df-457c-b9ae-8527f86c46eb"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-AlarmLow-00769bc8-6aeb-447b-a4d4-db8146a156f0
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-AlarmLow-00769bc8-6aeb-447b-a4d4-db8146a156f0"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-AlarmLow-cba45801-8523-44b0-a265-9230f8dd70ba
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-AlarmLow-cba45801-8523-44b0-a265-9230f8dd70ba"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-ProvisionedCapacityHigh-602676f4-c0de-4112-ae32-f06d0d28415a
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-ProvisionedCapacityHigh-602676f4-c0de-4112-ae32-f06d0d28415a"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-ProvisionedCapacityHigh-a5623180-de9f-4cf2-8b2e-1b0bfaf663db
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-ProvisionedCapacityHigh-a5623180-de9f-4cf2-8b2e-1b0bfaf663db"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-ProvisionedCapacityLow-3a2f6613-080b-4c5e-bb61-d6f4e1102bdd
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-ProvisionedCapacityLow-3a2f6613-080b-4c5e-bb61-d6f4e1102bdd"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users1_index_ByEmailAutoscale-ProvisionedCapacityLow-75d51f44-2a6b-4366-84a2-1f10d8d47013
  id = "TargetTracking-table/Users1/index/ByEmailAutoscale-ProvisionedCapacityLow-75d51f44-2a6b-4366-84a2-1f10d8d47013"
}

import {
  to = aws_dynamodb_table.Events-OnDemand1
  id = "Events-OnDemand1"
}

import {
  to = aws_dynamodb_table.Ledger1
  id = "Ledger1"
}

import {
  to = aws_dynamodb_table.Metrics-Autoscaling1
  id = "Metrics-Autoscaling1"
}

import {
  to = aws_dynamodb_table.Orders1
  id = "Orders1"
}

import {
  to = aws_dynamodb_table.Sessions1
  id = "Sessions1"
}

import {
  to = aws_dynamodb_table.Users1
  id = "Users1"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.StreamConsumer1_role
  id = "StreamConsumer1_role"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_lambda_event_source_mapping.LedgerStreamMapping1
  id = "5c5d9bf8-c0f4-454a-aba1-d8a5ea930955"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_lambda_function.StreamConsumer1
  id = "StreamConsumer1"
}

import {
  to = aws_kinesis_stream.LedgerKinesisStream1
  id = "LedgerKinesisStream1"
}
