# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_iam_policy.lambda_function_StreamConsumer_st_dynamodb-tour
  id = "arn:aws:iam::952133486861:policy/lambda_function_StreamConsumer_st_dynamodb-tour"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmHigh-14a8749a-6281-4ef5-9bb8-cadb3be3f0f2
  id = "TargetTracking-table/MetricsAutoscaling-AlarmHigh-14a8749a-6281-4ef5-9bb8-cadb3be3f0f2"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmHigh-4385b384-e780-4760-8c32-a9a88cef1db1
  id = "TargetTracking-table/MetricsAutoscaling-AlarmHigh-4385b384-e780-4760-8c32-a9a88cef1db1"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmLow-46fd7b3a-726d-487f-96bd-ecb13482c82b
  id = "TargetTracking-table/MetricsAutoscaling-AlarmLow-46fd7b3a-726d-487f-96bd-ecb13482c82b"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmLow-77d06b1c-c0fd-42ab-b836-54e9caf36b18
  id = "TargetTracking-table/MetricsAutoscaling-AlarmLow-77d06b1c-c0fd-42ab-b836-54e9caf36b18"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityHigh-b572fe79-4fcc-4a6b-95df-938201f6ce57
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityHigh-b572fe79-4fcc-4a6b-95df-938201f6ce57"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityHigh-f5c48e82-922f-42b4-b27f-5b68b25075d9
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityHigh-f5c48e82-922f-42b4-b27f-5b68b25075d9"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityLow-16e68986-7bdd-4bda-85a5-372f684630ef
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityLow-16e68986-7bdd-4bda-85a5-372f684630ef"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityLow-4a0573d2-aaad-4d4d-9e32-eea3d36b34c3
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityLow-4a0573d2-aaad-4d4d-9e32-eea3d36b34c3"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmHigh-2f283fb9-07ea-4002-a81a-bca4c3f1ddba
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmHigh-2f283fb9-07ea-4002-a81a-bca4c3f1ddba"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmHigh-ce9a62bf-f42e-42e3-953e-dab8756fa0a4
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmHigh-ce9a62bf-f42e-42e3-953e-dab8756fa0a4"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmLow-0e3e6039-fe34-4e85-b519-82090a7b096b
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmLow-0e3e6039-fe34-4e85-b519-82090a7b096b"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmLow-d9c1d386-fc3f-4946-bc9f-d3c28ad0ecdd
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmLow-d9c1d386-fc3f-4946-bc9f-d3c28ad0ecdd"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityHigh-4d64aca9-c474-4217-bbbf-199002c50a74
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityHigh-4d64aca9-c474-4217-bbbf-199002c50a74"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityHigh-9bc1923b-42b2-424d-aa79-1d6d8713f850
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityHigh-9bc1923b-42b2-424d-aa79-1d6d8713f850"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityLow-aa23f16c-c187-4f35-ab3f-693de27bda83
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityLow-aa23f16c-c187-4f35-ab3f-693de27bda83"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityLow-edf4153b-5581-43c0-ae85-955dde48b656
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityLow-edf4153b-5581-43c0-ae85-955dde48b656"
}

import {
  to = aws_dynamodb_table.EventsOnDemand
  id = "EventsOnDemand"
}

import {
  to = aws_dynamodb_table.Ledger
  id = "Ledger"
}

import {
  to = aws_dynamodb_table.MetricsAutoscaling
  id = "MetricsAutoscaling"
}

import {
  to = aws_dynamodb_table.Orders
  id = "Orders"
}

import {
  to = aws_dynamodb_table.RestoredLatest
  id = "RestoredLatest"
}

import {
  to = aws_dynamodb_table.RestoredPointInTime
  id = "RestoredPointInTime"
}

import {
  to = aws_dynamodb_table.Sessions
  id = "Sessions"
}

import {
  to = aws_dynamodb_table.Users
  id = "Users"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.StreamConsumer_role
  id = "StreamConsumer_role"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_lambda_event_source_mapping.LedgerStreamMapping
  id = "ee8fb5e1-0d3a-49d1-a280-02f7d4a5f201"
}

import {
  to = aws_lambda_function.StreamConsumer
  id = "StreamConsumer"
}

import {
  to = aws_cloudwatch_log_group.StreamConsumer
  id = "/aws/lambda/StreamConsumer"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_kinesis_stream.LedgerKinesisStream
  id = "LedgerKinesisStream"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_table_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_table_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:WriteCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_table_Users_index_ByEmailAutoscale
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_table_Users_index_ByEmailAutoscale
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:WriteCapacityUnits"
}

import {
  to = aws_dynamodb_kinesis_streaming_destination.Ledger_to_LedgerKinesisStream
  id = "Ledger,arn:aws:kinesis:us-west-2:952133486861:stream/LedgerKinesisStream"
}
