# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_iam_policy.lambda_function_StreamConsumer_st_dynamodb-tour
  id = "arn:aws:iam::952133486861:policy/lambda_function_StreamConsumer_st_dynamodb-tour"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmHigh-4a578ec7-db0a-488f-aab0-d4075dc8bd34
  id = "TargetTracking-table/MetricsAutoscaling-AlarmHigh-4a578ec7-db0a-488f-aab0-d4075dc8bd34"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmHigh-8631837b-b9c3-4560-a6f4-605fa776cc33
  id = "TargetTracking-table/MetricsAutoscaling-AlarmHigh-8631837b-b9c3-4560-a6f4-605fa776cc33"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmLow-88b87a19-aed6-41d0-8cc3-4629b9ea9286
  id = "TargetTracking-table/MetricsAutoscaling-AlarmLow-88b87a19-aed6-41d0-8cc3-4629b9ea9286"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-AlarmLow-ff2c374f-1f03-44d1-a1bd-d15016048004
  id = "TargetTracking-table/MetricsAutoscaling-AlarmLow-ff2c374f-1f03-44d1-a1bd-d15016048004"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityHigh-9aec925e-57a1-4d9b-88c0-73a0f6242f2d
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityHigh-9aec925e-57a1-4d9b-88c0-73a0f6242f2d"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityHigh-c20c159c-7c8c-4c39-b0b5-4e3ea2f0d22a
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityHigh-c20c159c-7c8c-4c39-b0b5-4e3ea2f0d22a"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityLow-10cfb48d-e827-47ab-a440-e3481a2cd751
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityLow-10cfb48d-e827-47ab-a440-e3481a2cd751"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_MetricsAutoscaling-ProvisionedCapacityLow-fde8e44e-2838-46ee-9216-67b561fd1f51
  id = "TargetTracking-table/MetricsAutoscaling-ProvisionedCapacityLow-fde8e44e-2838-46ee-9216-67b561fd1f51"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmHigh-37687427-86d7-4a86-b7e5-c4a54d579baf
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmHigh-37687427-86d7-4a86-b7e5-c4a54d579baf"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmHigh-d0fe770e-6e49-42d8-b123-db96862ed4d1
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmHigh-d0fe770e-6e49-42d8-b123-db96862ed4d1"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmLow-3d95c174-8eed-4232-825e-562a75555947
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmLow-3d95c174-8eed-4232-825e-562a75555947"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-AlarmLow-a0c3581a-5919-4e6e-9824-a5cc55fa1e10
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-AlarmLow-a0c3581a-5919-4e6e-9824-a5cc55fa1e10"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityHigh-4cddc6b8-98f7-4f59-ba08-823e81a948e9
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityHigh-4cddc6b8-98f7-4f59-ba08-823e81a948e9"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityHigh-aa0adbb2-69ce-4421-8633-f4d4e8ad8f12
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityHigh-aa0adbb2-69ce-4421-8633-f4d4e8ad8f12"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityLow-10b320ab-2258-4f3d-aafb-66b2e1054a7f
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityLow-10b320ab-2258-4f3d-aafb-66b2e1054a7f"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-table_Users_index_ByEmailAutoscale-ProvisionedCapacityLow-5426847e-8774-4fad-a628-8c32eb701d9c
  id = "TargetTracking-table/Users/index/ByEmailAutoscale-ProvisionedCapacityLow-5426847e-8774-4fad-a628-8c32eb701d9c"
}

import {
  to = aws_dynamodb_table.EventsOnDemand
  id = "EventsOnDemand"
}

import {
  to = aws_dynamodb_table.Ledger
  id = "Ledger"
}

import {
  to = aws_dynamodb_table.MetricsAutoscaling
  id = "MetricsAutoscaling"
}

import {
  to = aws_dynamodb_table.Orders
  id = "Orders"
}

import {
  to = aws_dynamodb_table.RestoredLatest
  id = "RestoredLatest"
}

import {
  to = aws_dynamodb_table.RestoredPointInTime
  id = "RestoredPointInTime"
}

import {
  to = aws_dynamodb_table.Sessions
  id = "Sessions"
}

import {
  to = aws_dynamodb_table.Users
  id = "Users"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_kinesis_stream.LedgerKinesisStream
  id = "LedgerKinesisStream"
}

import {
  to = aws_lambda_function.StreamConsumer
  id = "StreamConsumer"
}

import {
  to = aws_cloudwatch_log_group.StreamConsumer
  id = "/aws/lambda/StreamConsumer"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_iam_role.StreamConsumer_role
  id = "StreamConsumer_role"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_lambda_event_source_mapping.LedgerStreamMapping
  id = "c04d2eef-9469-423f-a227-11a16eb768ab"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_table_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_table_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:WriteCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_table_Users_index_ByEmailAutoscale
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_table_Users_index_ByEmailAutoscale
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:WriteCapacityUnits"
}

import {
  to = aws_dynamodb_kinesis_streaming_destination.Ledger_to_LedgerKinesisStream
  id = "Ledger,arn:aws:kinesis:us-west-2:952133486861:stream/LedgerKinesisStream"
}
