# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_s3_bucket.origem-cf-validacao
  id = "origem-cf-validacao"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_s3_bucket_abac.origem-cf-validacao_abac
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_accelerate_configuration.origem-cf-validacao_accelerate_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_cors_configuration.origem-cf-validacao_cors_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_lifecycle_configuration.origem-cf-validacao_lifecycle_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_logging.origem-cf-validacao_logging
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_metadata_configuration.origem-cf-validacao_metadata_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_notification.origem-cf-validacao_notification
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_object_lock_configuration.origem-cf-validacao_object_lock_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_ownership_controls.origem-cf-validacao_ownership_controls
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_public_access_block.origem-cf-validacao_public_access_block
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_request_payment_configuration.origem-cf-validacao_request_payment_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_server_side_encryption_configuration.origem-cf-validacao_server_side_encryption_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_versioning.origem-cf-validacao_versioning
  id = "origem-cf-validacao"
}
