# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_autoscaling_group.oregon-asg-group
  id = "oregon-asg-group"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1
  id = "TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593
  id = "TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593"
}

import {
  to = aws_egress_only_internet_gateway.eigw-083dc9b065af87635
  id = "eigw-083dc9b065af87635"
}

import {
  to = aws_network_acl.oregon-asg-nacl
  id = "acl-09b3a9f00f5142610"
}

import {
  to = aws_security_group.oregon-asg-nodes
  id = "sg-03276c140e8a25c32"
}

import {
  to = aws_route_table.oregon-net-rt-private-b
  id = "rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table.oregon-net-rt-public
  id = "rtb-06de1785070037b00"
}

import {
  to = aws_route_table.oregon-net-rt-private-c
  id = "rtb-09104aa275e57925a"
}

import {
  to = aws_route_table.oregon-net-rt-private-a
  id = "rtb-08f9cf7f023267381"
}

import {
  to = aws_launch_template.lt-0c672bbb12a42eab9
  id = "lt-0c672bbb12a42eab9"
}

import {
  to = aws_subnet.oregon-net-public-b
  id = "subnet-0897192a2fe08a7e9"
}

import {
  to = aws_subnet.oregon-net-public-a
  id = "subnet-00779ed65ce3f7870"
}

import {
  to = aws_subnet.oregon-net-private-b
  id = "subnet-0592d1e9583f7bbcb"
}

import {
  to = aws_subnet.oregon-net-private-a
  id = "subnet-0930bc02de849cf54"
}

import {
  to = aws_subnet.oregon-net-public-c
  id = "subnet-03a4a9adc0cb3b101"
}

import {
  to = aws_subnet.oregon-net-private-c
  id = "subnet-08d0bbf639413d65c"
}

import {
  to = aws_vpc.oregon-net-vpc
  id = "vpc-0a43534eefc21fcb1"
}

import {
  to = aws_vpc.oregon-asg-vpc2
  id = "vpc-0b2cb48f01ccce0c2"
}

import {
  to = aws_vpc_endpoint.vpce-07b8c24111b4f21ca
  id = "vpce-07b8c24111b4f21ca"
}

import {
  to = aws_vpc_endpoint.vpce-01809868ad046f260
  id = "vpce-01809868ad046f260"
}

import {
  to = aws_vpc_peering_connection.pcx-0659fe288fc855311
  id = "pcx-0659fe288fc855311"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_internet_gateway.oregon-net-igw
  id = "igw-0fc6487d32e5b1fea"
}

import {
  to = aws_route_table_association.subnet-0592d1e9583f7bbcb_rtb-060eaf458d6754e72
  id = "subnet-0592d1e9583f7bbcb/rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table_association.subnet-00779ed65ce3f7870_rtb-06de1785070037b00
  id = "subnet-00779ed65ce3f7870/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-03a4a9adc0cb3b101_rtb-06de1785070037b00
  id = "subnet-03a4a9adc0cb3b101/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-0897192a2fe08a7e9_rtb-06de1785070037b00
  id = "subnet-0897192a2fe08a7e9/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-08d0bbf639413d65c_rtb-09104aa275e57925a
  id = "subnet-08d0bbf639413d65c/rtb-09104aa275e57925a"
}

import {
  to = aws_route_table_association.subnet-0930bc02de849cf54_rtb-08f9cf7f023267381
  id = "subnet-0930bc02de849cf54/rtb-08f9cf7f023267381"
}

import {
  to = aws_network_acl_rule.out_acl-09b3a9f00f5142610_100
  id = "acl-09b3a9f00f5142610:100:-1:true"
}

import {
  to = aws_network_acl_rule.in_acl-09b3a9f00f5142610_100
  id = "acl-09b3a9f00f5142610:100:6:false"
}

import {
  to = aws_network_acl_rule.in_acl-09b3a9f00f5142610_110
  id = "acl-09b3a9f00f5142610:110:6:false"
}

import {
  to = aws_service_discovery_private_dns_namespace.oregon-net-vpc_namespace
  id = "vpc-0a43534eefc21fcb1"
}

import {
  to = aws_service_discovery_private_dns_namespace.oregon-asg-vpc2_namespace
  id = "vpc-0b2cb48f01ccce0c2"
}
