# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_internet_gateway.internet-gateway
  id = "igw-0c21d09de6b7ab84c"
}

import {
  to = aws_launch_template.web-server-launch-template
  id = "lt-0d6e73a1434f8d838"
}

import {
  to = aws_lb_listener.http-listener
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:listener/app/application-load-balancer/2b0ab14600dda1c1/720b7f319126eff1"
}

import {
  to = aws_lb_target_group.web-target-group
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/web-target-group/fa33c1c324570f6f"
}

import {
  to = aws_route_table.private-route-table
  id = "rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table.public-route-table
  id = "rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_subnet.private-subnet-a
  id = "subnet-04f8936bbb980e2da"
}

import {
  to = aws_autoscaling_group.web-server-asg
  id = "web-server-asg"
}

import {
  to = aws_subnet.public-subnet-a
  id = "subnet-0fc79f8b9a5540bcf"
}

import {
  to = aws_instance.nat-instance
  id = "i-0fefd2d2339113deb"
}

import {
  to = aws_lb.application-load-balancer
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:loadbalancer/app/application-load-balancer/2b0ab14600dda1c1"
}

import {
  to = aws_subnet.private-subnet-b
  id = "subnet-0caa31b67692392d1"
}

import {
  to = aws_subnet.public-subnet-b
  id = "subnet-04161fb5562953ab3"
}

import {
  to = aws_subnet.private-subnet-c
  id = "subnet-0113c2ad2bc2f618c"
}

import {
  to = aws_subnet.public-subnet-c
  id = "subnet-0323b25f47f36503d"
}

import {
  to = aws_vpc.alb-web-servers
  id = "vpc-05948e9b0f8b42ce4"
}

import {
  to = aws_security_group.autoscaling_group_web-server-asg_group
  id = "sg-02dff097b8b6311e8"
}

import {
  to = aws_iam_role.web-server-asg_role
  id = "web-server-asg_role"
}

import {
  to = aws_iam_instance_profile.web-server-asg_profile
  id = "web-server-asg_profile"
}

import {
  to = aws_security_group.instance_nat-instance_group
  id = "sg-086e28b685da2a2cc"
}

import {
  to = aws_iam_role.nat-instance_role
  id = "nat-instance_role"
}

import {
  to = aws_iam_instance_profile.nat-instance_profile
  id = "nat-instance_profile"
}

import {
  to = aws_security_group.lb_application-load-balancer_group
  id = "sg-00a01184ad0fd7e42"
}

import {
  to = aws_route.route_private-route-table_to_nat-instance_ipv4
  id = "rtb-0c14faad417d3dac9_0.0.0.0/0"
}

import {
  to = aws_route.route_public-route-table_to_internet-gateway_ipv4
  id = "rtb-0e7ef9f24d26b8594_0.0.0.0/0"
}

import {
  to = aws_route_table_association.aws_route_table_association_private_subnet_a_private_route_table
  id = "subnet-04f8936bbb980e2da/rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table_association.aws_route_table_association_private_subnet_b_private_route_table
  id = "subnet-0caa31b67692392d1/rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table_association.aws_route_table_association_private_subnet_c_private_route_table
  id = "subnet-0113c2ad2bc2f618c/rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_subnet_a_public_route_table
  id = "subnet-0fc79f8b9a5540bcf/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_subnet_b_public_route_table
  id = "subnet-04161fb5562953ab3/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_subnet_c_public_route_table
  id = "subnet-0323b25f47f36503d/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_security_group_rule.rule_autoscaling_group_web_server_asg_group_egress_all_protocols
  id = "sg-02dff097b8b6311e8_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_instance_nat_instance_group_egress_all_protocols
  id = "sg-086e28b685da2a2cc_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_instance_nat_instance_group_ingress_all_protocols
  id = "sg-086e28b685da2a2cc_ingress_all_0_0_10.3.0.0/16"
}

import {
  to = aws_security_group_rule.rule_lb_application_load_balancer_group_egress_all_protocols
  id = "sg-00a01184ad0fd7e42_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_lb_application_load_balancer_group_ingress_all_protocols
  id = "sg-00a01184ad0fd7e42_ingress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_lb_application_load_balancer_group_to_autoscaling_group_web_server_asg_group_tcp_80
  id = "sg-02dff097b8b6311e8_ingress_tcp_80_80_sg-00a01184ad0fd7e42"
}
