# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_egress_only_internet_gateway.eigw-083dc9b065af87635
  id = "eigw-083dc9b065af87635"
}

import {
  to = aws_internet_gateway.oregon-net2-igw
  id = "igw-077c438d94d10e59b"
}

import {
  to = aws_route_table.oregon-net2-rt-private
  id = "rtb-0c6184284969a00c5"
}

import {
  to = aws_route_table.oregon-net2-rt-public
  id = "rtb-0c705143390c67c84"
}

import {
  to = aws_security_group.oregon-net2-web
  id = "sg-0f1a0f13ed322cb04"
}

import {
  to = aws_vpc_endpoint.oregon-net2-vpce-s3_S3
  id = "vpce-0cde8acf19edb615d"
}

import {
  to = aws_subnet.oregon-net2-private-c
  id = "subnet-095560e83fe6e09c7"
}

import {
  to = aws_subnet.oregon-net2-public-a
  id = "subnet-02517976ff0ad9701"
}

import {
  to = aws_network_acl.oregon-net2-nacl
  id = "acl-04ffdad4553bd4409"
}

import {
  to = aws_subnet.oregon-net2-public-b
  id = "subnet-0f8ad4914ec119bb0"
}

import {
  to = aws_vpc.oregon-asg-vpc2
  id = "vpc-0b2cb48f01ccce0c2"
}

import {
  to = aws_route.route_oregon-net2-rt-public_to_oregon-net2-igw_ipv4
  id = "rtb-0c705143390c67c84_0.0.0.0/0"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net2_private_c_oregon_net2_rt_private
  id = "subnet-095560e83fe6e09c7/rtb-0c6184284969a00c5"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net2_public_a_oregon_net2_rt_public
  id = "subnet-02517976ff0ad9701/rtb-0c705143390c67c84"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net2_public_b_oregon_net2_rt_public
  id = "subnet-0f8ad4914ec119bb0/rtb-0c705143390c67c84"
}

import {
  to = aws_network_acl_rule.in_acl-04ffdad4553bd4409_100_ingress_0_0_0_0_0_tcp_port_443
  id = "acl-04ffdad4553bd4409:100:tcp:false"
}

import {
  to = aws_network_acl_rule.in_acl-04ffdad4553bd4409_110_ingress_0_0_0_0_0_tcp_ports_1024_65535
  id = "acl-04ffdad4553bd4409:110:tcp:false"
}

import {
  to = aws_network_acl_rule.out_acl-04ffdad4553bd4409_100_egress_0_0_0_0_0_all_proto
  id = "acl-04ffdad4553bd4409:100:-1:true"
}

import {
  to = aws_security_group_rule.rule_oregon_net2_web_egress_all_protocols
  id = "sg-0f1a0f13ed322cb04_egress_all_0_0_0.0.0.0/0_::/0"
}

import {
  to = aws_security_group_rule.rule_oregon_net2_web_ingress_tcp_443
  id = "sg-0f1a0f13ed322cb04_ingress_tcp_443_443_10.30.0.0/16"
}

import {
  to = aws_security_group_rule.rule_oregon_net2_web_ingress_tcp_80
  id = "sg-0f1a0f13ed322cb04_ingress_tcp_80_80_10.20.0.0/16"
}
