# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_vpc_peering_connection.pcx-0659fe288fc855311
  id = "pcx-0659fe288fc855311"
}

import {
  to = aws_route.route_oregon-net-rt-public_to_pcx-0659fe288fc855311_10_30_0_0_16
  id = "rtb-06de1785070037b00_10.30.0.0/16"
}
