# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_internet_gateway.oregon-net-igw
  id = "igw-03b764cbfc490a6f4"
}

import {
  to = aws_route_table.oregon-net-rt-private-c
  id = "rtb-020f9e0285e209898"
}

import {
  to = aws_route_table.oregon-net-rt-private-a
  id = "rtb-0013b754ea5b3856e"
}

import {
  to = aws_route_table.oregon-net-rt-private-b
  id = "rtb-078dbca4ff584a263"
}

import {
  to = aws_route_table.oregon-net-rt-public
  id = "rtb-0d8dc70f2866e4817"
}

import {
  to = aws_subnet.oregon-net-private-a
  id = "subnet-0ebae2b1dcd8d670a"
}

import {
  to = aws_subnet.oregon-net-private-c
  id = "subnet-00368fa551aff38a7"
}

import {
  to = aws_subnet.oregon-net-public-b
  id = "subnet-002ecd3b1cf3d5eb4"
}

import {
  to = aws_subnet.oregon-net-public-a
  id = "subnet-0a5c8955d5e72c0c9"
}

import {
  to = aws_subnet.oregon-net-private-b
  id = "subnet-0c02c279a3ae3d707"
}

import {
  to = aws_subnet.oregon-net-public-c
  id = "subnet-02eeb68f1410e944a"
}

import {
  to = aws_vpc.oregon-net-vpc
  id = "vpc-08828afdee9c7b661"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_vpc_endpoint.vpce-09dc472bb42530361
  id = "vpce-09dc472bb42530361"
}

import {
  to = aws_vpc_endpoint.vpce-07f4715db4bd4c1cb
  id = "vpce-07f4715db4bd4c1cb"
}

import {
  to = aws_route_table_association.subnet-00368fa551aff38a7_rtb-020f9e0285e209898
  id = "subnet-00368fa551aff38a7/rtb-020f9e0285e209898"
}

import {
  to = aws_route_table_association.subnet-0ebae2b1dcd8d670a_rtb-0013b754ea5b3856e
  id = "subnet-0ebae2b1dcd8d670a/rtb-0013b754ea5b3856e"
}

import {
  to = aws_route_table_association.subnet-0c02c279a3ae3d707_rtb-078dbca4ff584a263
  id = "subnet-0c02c279a3ae3d707/rtb-078dbca4ff584a263"
}

import {
  to = aws_route_table_association.subnet-02eeb68f1410e944a_rtb-0d8dc70f2866e4817
  id = "subnet-02eeb68f1410e944a/rtb-0d8dc70f2866e4817"
}

import {
  to = aws_route_table_association.subnet-002ecd3b1cf3d5eb4_rtb-0d8dc70f2866e4817
  id = "subnet-002ecd3b1cf3d5eb4/rtb-0d8dc70f2866e4817"
}

import {
  to = aws_route_table_association.subnet-0a5c8955d5e72c0c9_rtb-0d8dc70f2866e4817
  id = "subnet-0a5c8955d5e72c0c9/rtb-0d8dc70f2866e4817"
}

import {
  to = aws_service_discovery_private_dns_namespace.oregon-net-vpc_namespace
  id = "vpc-08828afdee9c7b661"
}
