# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_cloudfront_cache_policy.d94ba52f-d2dd-457b-be05-c39fdffa4887
  id = "d94ba52f-d2dd-457b-be05-c39fdffa4887"
}

import {
  to = aws_cloudfront_function.viewer-request-kvs1
  id = "viewer-request-kvs1"
}

import {
  to = aws_cloudfront_key_value_store.kvs-validacao
  id = "kvs-validacao"
}

import {
  to = aws_cloudfront_distribution.cdn-protegida
  id = "E2ZGVTSXA8U5X0"
}

import {
  to = aws_cloudfront_distribution.cdn-aberta
  id = "E3RF0AX60CH06U"
}

import {
  to = aws_cloudfront_origin_access_control.E2GVSDJINEEAL7
  id = "E2GVSDJINEEAL7"
}

import {
  to = aws_cloudfront_origin_request_policy.ac6c4267-205d-4536-a7fa-2031976f9a9c
  id = "ac6c4267-205d-4536-a7fa-2031976f9a9c"
}

import {
  to = aws_cloudfront_public_key.K333AWWOV9UGSL
  id = "K333AWWOV9UGSL"
}

import {
  to = aws_cloudfront_key_group.db24cd5b-8958-4a8d-b9df-9b12ae1e2710
  id = "db24cd5b-8958-4a8d-b9df-9b12ae1e2710"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_s3_bucket.origem-cf-validacao
  id = "origem-cf-validacao"
}

import {
  to = aws_cloudfront_response_headers_policy.r_2725d2ab-6e3b-4264-b49a-ae24ee6d2800
  id = "2725d2ab-6e3b-4264-b49a-ae24ee6d2800"
}

import {
  to = aws_cloudfront_monitoring_subscription.cdn-protegida_subscription
  id = "E2ZGVTSXA8U5X0"
}

import {
  to = aws_cloudfront_monitoring_subscription.cdn-aberta_subscription
  id = "E3RF0AX60CH06U"
}

import {
  to = aws_s3_bucket_abac.origem-cf-validacao_abac
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_accelerate_configuration.origem-cf-validacao_accelerate_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_cors_configuration.origem-cf-validacao_cors_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_lifecycle_configuration.origem-cf-validacao_lifecycle_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_logging.origem-cf-validacao_logging
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_metadata_configuration.origem-cf-validacao_metadata_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_notification.origem-cf-validacao_notification
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_object_lock_configuration.origem-cf-validacao_object_lock_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_ownership_controls.origem-cf-validacao_ownership_controls
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_public_access_block.origem-cf-validacao_public_access_block
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_request_payment_configuration.origem-cf-validacao_request_payment_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_server_side_encryption_configuration.origem-cf-validacao_server_side_encryption_configuration
  id = "origem-cf-validacao"
}

import {
  to = aws_s3_bucket_versioning.origem-cf-validacao_versioning
  id = "origem-cf-validacao"
}
