# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1
  id = "TargetTracking-oregon-asg-group-AlarmHigh-e7c4c194-70b2-42d9-97e1-6be2ecfb75b1"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593
  id = "TargetTracking-oregon-asg-group-AlarmLow-fd52bd60-2ef8-4aee-b3c2-b26fe987d593"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_vpc.oregon-asg-vpc2
  id = "vpc-0b2cb48f01ccce0c2"
}

import {
  to = aws_egress_only_internet_gateway.eigw-083dc9b065af87635
  id = "eigw-083dc9b065af87635"
}

import {
  to = aws_route_table.oregon-net-rt-public
  id = "rtb-06de1785070037b00"
}

import {
  to = aws_vpc.oregon-net-vpc
  id = "vpc-0a43534eefc21fcb1"
}

import {
  to = aws_internet_gateway.oregon-net-igw
  id = "igw-0fc6487d32e5b1fea"
}

import {
  to = aws_launch_template.lt-0c672bbb12a42eab9
  id = "lt-0c672bbb12a42eab9"
}

import {
  to = aws_route_table.oregon-net-rt-private-a
  id = "rtb-08f9cf7f023267381"
}

import {
  to = aws_route_table.oregon-net-rt-private-b
  id = "rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table.oregon-net-rt-private-c
  id = "rtb-09104aa275e57925a"
}

import {
  to = aws_vpc_endpoint.oregon-net-vpce-dynamodb_DynamoDB
  id = "vpce-01809868ad046f260"
}

import {
  to = aws_vpc_endpoint.oregon-net-vpce-s3_S3
  id = "vpce-07b8c24111b4f21ca"
}

import {
  to = aws_subnet.oregon-net-private-a
  id = "subnet-0930bc02de849cf54"
}

import {
  to = aws_autoscaling_group.oregon-asg-group
  id = "oregon-asg-group"
}

import {
  to = aws_subnet.oregon-net-public-a
  id = "subnet-00779ed65ce3f7870"
}

import {
  to = aws_network_acl.oregon-asg-nacl
  id = "acl-09b3a9f00f5142610"
}

import {
  to = aws_subnet.oregon-net-private-b
  id = "subnet-0592d1e9583f7bbcb"
}

import {
  to = aws_subnet.oregon-net-public-b
  id = "subnet-0897192a2fe08a7e9"
}

import {
  to = aws_subnet.oregon-net-private-c
  id = "subnet-08d0bbf639413d65c"
}

import {
  to = aws_subnet.oregon-net-public-c
  id = "subnet-03a4a9adc0cb3b101"
}

import {
  to = aws_vpc_peering_connection.pcx-0659fe288fc855311
  id = "pcx-0659fe288fc855311"
}

import {
  to = aws_security_group.oregon-asg-nodes
  id = "sg-03276c140e8a25c32"
}

import {
  to = aws_route.route_oregon-net-rt-public_to_pcx-0659fe288fc855311_10_20_0_0_16
  id = "rtb-06de1785070037b00_10.20.0.0/16"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_a_oregon_net_rt_private_a
  id = "subnet-0930bc02de849cf54/rtb-08f9cf7f023267381"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_b_oregon_net_rt_private_b
  id = "subnet-0592d1e9583f7bbcb/rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_c_oregon_net_rt_private_c
  id = "subnet-08d0bbf639413d65c/rtb-09104aa275e57925a"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_a_oregon_net_rt_public
  id = "subnet-00779ed65ce3f7870/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_b_oregon_net_rt_public
  id = "subnet-0897192a2fe08a7e9/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_c_oregon_net_rt_public
  id = "subnet-03a4a9adc0cb3b101/rtb-06de1785070037b00"
}

import {
  to = aws_network_acl_rule.in_acl-09b3a9f00f5142610_100_ingress_0_0_0_0_0_tcp_port_443
  id = "acl-09b3a9f00f5142610:100:tcp:false"
}

import {
  to = aws_network_acl_rule.in_acl-09b3a9f00f5142610_110_ingress_0_0_0_0_0_tcp_ports_1024_65535
  id = "acl-09b3a9f00f5142610:110:tcp:false"
}

import {
  to = aws_network_acl_rule.in_infra_return_tcp_oregon-asg-nacl
  id = "acl-09b3a9f00f5142610:1001:tcp:false"
}

import {
  to = aws_network_acl_rule.in_infra_return_udp_oregon-asg-nacl
  id = "acl-09b3a9f00f5142610:1002:udp:false"
}

import {
  to = aws_network_acl_rule.out_infra_oregon-asg-nacl_port_123_udp
  id = "acl-09b3a9f00f5142610:23233:udp:true"
}

import {
  to = aws_network_acl_rule.out_infra_oregon-asg-nacl_port_443_tcp
  id = "acl-09b3a9f00f5142610:28986:tcp:true"
}

import {
  to = aws_network_acl_rule.out_infra_oregon-asg-nacl_port_53_tcp
  id = "acl-09b3a9f00f5142610:29875:tcp:true"
}

import {
  to = aws_network_acl_rule.out_infra_oregon-asg-nacl_port_53_udp
  id = "acl-09b3a9f00f5142610:15340:udp:true"
}

import {
  to = aws_security_group_rule.rule_oregon_asg_nodes_egress_all_protocols
  id = "sg-03276c140e8a25c32_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_oregon_asg_nodes_ingress_tcp_443
  id = "sg-03276c140e8a25c32_ingress_tcp_443_443_10.20.0.0/16"
}
