# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_vpc.oregon-asg-vpc2
  id = "vpc-0b2cb48f01ccce0c2"
}

import {
  to = aws_route_table.oregon-net-rt-public
  id = "rtb-06de1785070037b00"
}

import {
  to = aws_vpc.oregon-net-vpc
  id = "vpc-0a43534eefc21fcb1"
}

import {
  to = aws_internet_gateway.oregon-net-igw
  id = "igw-0fc6487d32e5b1fea"
}

import {
  to = aws_route_table.oregon-net-rt-private-a
  id = "rtb-08f9cf7f023267381"
}

import {
  to = aws_route_table.oregon-net-rt-private-b
  id = "rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table.oregon-net-rt-private-c
  id = "rtb-09104aa275e57925a"
}

import {
  to = aws_vpc_endpoint.oregon-net-vpce-dynamodb_DynamoDB
  id = "vpce-01809868ad046f260"
}

import {
  to = aws_vpc_endpoint.oregon-net-vpce-s3_S3
  id = "vpce-07b8c24111b4f21ca"
}

import {
  to = aws_subnet.oregon-net-private-a
  id = "subnet-0930bc02de849cf54"
}

import {
  to = aws_subnet.oregon-net-public-a
  id = "subnet-00779ed65ce3f7870"
}

import {
  to = aws_subnet.oregon-net-private-b
  id = "subnet-0592d1e9583f7bbcb"
}

import {
  to = aws_subnet.oregon-net-public-b
  id = "subnet-0897192a2fe08a7e9"
}

import {
  to = aws_subnet.oregon-net-private-c
  id = "subnet-08d0bbf639413d65c"
}

import {
  to = aws_subnet.oregon-net-public-c
  id = "subnet-03a4a9adc0cb3b101"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_a_oregon_net_rt_private_a
  id = "subnet-0930bc02de849cf54/rtb-08f9cf7f023267381"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_b_oregon_net_rt_private_b
  id = "subnet-0592d1e9583f7bbcb/rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_private_c_oregon_net_rt_private_c
  id = "subnet-08d0bbf639413d65c/rtb-09104aa275e57925a"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_a_oregon_net_rt_public
  id = "subnet-00779ed65ce3f7870/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_b_oregon_net_rt_public
  id = "subnet-0897192a2fe08a7e9/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.aws_route_table_association_oregon_net_public_c_oregon_net_rt_public
  id = "subnet-03a4a9adc0cb3b101/rtb-06de1785070037b00"
}
