# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_cloudwatch_log_group.aws_lambda_us-east-1_Redirector
  id = "/aws/lambda/us-east-1.Redirector"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_vpc.loadtest-asg-simple
  id = "vpc-0653bd333a0ed7467"
}

import {
  to = aws_autoscaling_policy.cpu-scale
  id = "hub-asg/cpu-scale"
}

import {
  to = aws_internet_gateway.igw-k6
  id = "igw-0de941d6034969d71"
}

import {
  to = aws_launch_template.hub-lt
  id = "lt-073fde5b15179c97a"
}

import {
  to = aws_lb_listener.listener-dashboard
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:listener/app/alb-hub/1656aa1072071160/70de74e7cb6ce34e"
}

import {
  to = aws_lb_listener.listener-http
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:listener/app/alb-hub/1656aa1072071160/591998af073b761e"
}

import {
  to = aws_lb_target_group.tg-hub
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/tg-hub/8e9e0b35eb31b027"
}

import {
  to = aws_lb_target_group.tg-k6-dashboard
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/tg-k6-dashboard/19c75c81216fe779"
}

import {
  to = aws_route_table.rt-private1
  id = "rtb-08a0f20f8b804daee"
}

import {
  to = aws_route_table.rt-public1
  id = "rtb-097a554277412a32d"
}

import {
  to = aws_subnet.private-a
  id = "subnet-08c4636ea47bf6433"
}

import {
  to = aws_autoscaling_group.hub-asg
  id = "hub-asg"
}

import {
  to = aws_subnet.public-a
  id = "subnet-02e7f98fc851a0425"
}

import {
  to = aws_instance.nat-a
  id = "i-0f98815030ddadd3f"
}

import {
  to = aws_lb.alb-hub
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:loadbalancer/app/alb-hub/1656aa1072071160"
}

import {
  to = aws_subnet.public-k6
  id = "subnet-072d0c7c7c205aeb8"
}

import {
  to = aws_instance.k6-load-generator
  id = "i-0a5ff1e001ff4ea7a"
}

import {
  to = aws_subnet.private-b
  id = "subnet-078c5075cd52a3139"
}

import {
  to = aws_subnet.public-b
  id = "subnet-04f96472629243fd2"
}

import {
  to = aws_security_group.autoscaling_group_hub-asg_group
  id = "sg-0f00e047b305fb386"
}

import {
  to = aws_security_group.instance_nat-a_group
  id = "sg-095276e284fb4c8a9"
}

import {
  to = aws_iam_role.nat-a_role
  id = "nat-a_role"
}

import {
  to = aws_iam_instance_profile.nat-a_profile
  id = "nat-a_profile"
}

import {
  to = aws_security_group.instance_k6-load-generator_group
  id = "sg-0de36f4876c9ce72c"
}

import {
  to = aws_iam_role.k6-load-generator_role
  id = "k6-load-generator_role"
}

import {
  to = aws_iam_instance_profile.k6-load-generator_profile
  id = "k6-load-generator_profile"
}

import {
  to = aws_route.route_rt-private1_to_nat-a_ipv4
  id = "rtb-08a0f20f8b804daee_0.0.0.0/0"
}

import {
  to = aws_route.route_rt-public1_to_igw-k6_ipv4
  id = "rtb-097a554277412a32d_0.0.0.0/0"
}

import {
  to = aws_route_table_association.aws_route_table_association_private_a_rt_private1
  id = "subnet-08c4636ea47bf6433/rtb-08a0f20f8b804daee"
}

import {
  to = aws_route_table_association.aws_route_table_association_private_b_rt_private1
  id = "subnet-078c5075cd52a3139/rtb-08a0f20f8b804daee"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_a_rt_public1
  id = "subnet-02e7f98fc851a0425/rtb-097a554277412a32d"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_b_rt_public1
  id = "subnet-04f96472629243fd2/rtb-097a554277412a32d"
}

import {
  to = aws_route_table_association.aws_route_table_association_public_k6_rt_public1
  id = "subnet-072d0c7c7c205aeb8/rtb-097a554277412a32d"
}

import {
  to = aws_security_group_rule.rule_autoscaling_group_hub_asg_group_egress_all_protocols
  id = "sg-0f00e047b305fb386_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_autoscaling_group_hub_asg_group_ingress_tcp_8080
  id = "sg-0f00e047b305fb386_ingress_tcp_8080_8080_10.60.0.0/16"
}

import {
  to = aws_security_group_rule.rule_instance_k6_load_generator_group_egress_all_protocols
  id = "sg-0de36f4876c9ce72c_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_instance_k6_load_generator_group_ingress_tcp_5665
  id = "sg-0de36f4876c9ce72c_ingress_tcp_5665_5665_10.60.0.0/16"
}

import {
  to = aws_security_group_rule.rule_instance_nat_a_group_egress_all_protocols
  id = "sg-095276e284fb4c8a9_egress_all_0_0_0.0.0.0/0"
}

import {
  to = aws_security_group_rule.rule_instance_nat_a_group_ingress_all_protocols
  id = "sg-095276e284fb4c8a9_ingress_all_0_0_10.60.0.0/16"
}

import {
  to = aws_security_group_rule.rule_instance_nat_a_group_ingress_tcp_5665
  id = "sg-095276e284fb4c8a9_ingress_tcp_5665_5665_0.0.0.0/0"
}

import {
  to = aws_lb_target_group_attachment.attach_k6-load-generator_to_tg-k6-dashboard
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/tg-k6-dashboard/19c75c81216fe779,i-0a5ff1e001ff4ea7a,5665"
}
