# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_cloudwatch_log_group.StreamConsumer
  id = "/aws/lambda/StreamConsumer"
}

import {
  to = aws_dynamodb_kinesis_streaming_destination.Ledger_to_LedgerKinesisStream
  id = "Ledger,arn:aws:kinesis:us-west-2:952133486861:stream/LedgerKinesisStream"
}

import {
  to = aws_dynamodb_table.EventsOnDemand
  id = "EventsOnDemand"
}

import {
  to = aws_dynamodb_table.Ledger
  id = "Ledger"
}

import {
  to = aws_dynamodb_table.MetricsAutoscaling
  id = "MetricsAutoscaling"
}

import {
  to = aws_dynamodb_table.Orders
  id = "Orders"
}

import {
  to = aws_dynamodb_table.RestoredLatest
  id = "RestoredLatest"
}

import {
  to = aws_dynamodb_table.RestoredPointInTime
  id = "RestoredPointInTime"
}

import {
  to = aws_dynamodb_table.Sessions
  id = "Sessions"
}

import {
  to = aws_dynamodb_table.Users
  id = "Users"
}

import {
  to = aws_kinesis_stream.LedgerKinesisStream
  id = "LedgerKinesisStream"
}

import {
  to = aws_lambda_event_source_mapping.LedgerStreamMapping
  id = "ee8fb5e1-0d3a-49d1-a280-02f7d4a5f201"
}

import {
  to = aws_lambda_function.StreamConsumer
  id = "StreamConsumer"
}

import {
  to = aws_iam_role.StreamConsumer_role
  id = "StreamConsumer_role"
}

import {
  to = aws_iam_policy.lambda_function_StreamConsumer_st_dynamodb-tour
  id = "arn:aws:iam::952133486861:policy/lambda_function_StreamConsumer_st_dynamodb-tour"
}

import {
  to = aws_iam_role_policy_attachment.lambda_function_StreamConsumer_st_dynamodb-tour_attach_StreamConsumer_role
  id = "StreamConsumer_role/arn:aws:iam::952133486861:policy/lambda_function_StreamConsumer_st_dynamodb-tour"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_ByEmailAutoscale_Users
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Read_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:ReadCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_ByEmailAutoscale_Users
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:WriteCapacityUnits"
}

import {
  to = aws_appautoscaling_target.sc_target_Write_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:WriteCapacityUnits"
}

import {
  to = aws_appautoscaling_policy.sc_policy_Read_ByEmailAutoscale_Users
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:ReadCapacityUnits/DynamoDBReadCapacityUtilization:sc_target_Read_ByEmailAutoscale_Users"
}

import {
  to = aws_appautoscaling_policy.sc_policy_Read_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:ReadCapacityUnits/DynamoDBReadCapacityUtilization:sc_target_Read_MetricsAutoscaling"
}

import {
  to = aws_appautoscaling_policy.sc_policy_Write_ByEmailAutoscale_Users
  id = "dynamodb/table/Users/index/ByEmailAutoscale/dynamodb:index:WriteCapacityUnits/DynamoDBWriteCapacityUtilization:sc_target_Write_ByEmailAutoscale_Users"
}

import {
  to = aws_appautoscaling_policy.sc_policy_Write_MetricsAutoscaling
  id = "dynamodb/table/MetricsAutoscaling/dynamodb:table:WriteCapacityUnits/DynamoDBWriteCapacityUtilization:sc_target_Write_MetricsAutoscaling"
}
