# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_vpc_endpoint.vpce-07b8c24111b4f21ca
  id = "vpce-07b8c24111b4f21ca"
}

import {
  to = aws_vpc_endpoint.vpce-01809868ad046f260
  id = "vpce-01809868ad046f260"
}

import {
  to = aws_route_table_association.subnet-0592d1e9583f7bbcb_rtb-060eaf458d6754e72
  id = "subnet-0592d1e9583f7bbcb/rtb-060eaf458d6754e72"
}

import {
  to = aws_route_table_association.subnet-00779ed65ce3f7870_rtb-06de1785070037b00
  id = "subnet-00779ed65ce3f7870/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-0897192a2fe08a7e9_rtb-06de1785070037b00
  id = "subnet-0897192a2fe08a7e9/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-03a4a9adc0cb3b101_rtb-06de1785070037b00
  id = "subnet-03a4a9adc0cb3b101/rtb-06de1785070037b00"
}

import {
  to = aws_route_table_association.subnet-08d0bbf639413d65c_rtb-09104aa275e57925a
  id = "subnet-08d0bbf639413d65c/rtb-09104aa275e57925a"
}

import {
  to = aws_route_table_association.subnet-0930bc02de849cf54_rtb-08f9cf7f023267381
  id = "subnet-0930bc02de849cf54/rtb-08f9cf7f023267381"
}
