# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_internet_gateway.internet-gateway
  id = "igw-0c21d09de6b7ab84c"
}

import {
  to = aws_launch_template.lt-0d6e73a1434f8d838
  id = "lt-0d6e73a1434f8d838"
}

import {
  to = aws_instance.i-0f68442ea37a89af1
  id = "i-0f68442ea37a89af1"
}

import {
  to = aws_instance.i-0492eb0a111f90cb4
  id = "i-0492eb0a111f90cb4"
}

import {
  to = aws_instance.i-0fefd2d2339113deb
  id = "i-0fefd2d2339113deb"
}

import {
  to = aws_instance.i-098716def4aed0757
  id = "i-098716def4aed0757"
}

import {
  to = aws_route_table.public-route-table
  id = "rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table.private-route-table
  id = "rtb-0c14faad417d3dac9"
}

import {
  to = aws_security_group.autoscaling_group_web-server-asg_group
  id = "sg-02dff097b8b6311e8"
}

import {
  to = aws_security_group.lb_application-load-balancer_group
  id = "sg-00a01184ad0fd7e42"
}

import {
  to = aws_security_group.instance_nat-instance_group
  id = "sg-086e28b685da2a2cc"
}

import {
  to = aws_vpc.alb-web-servers
  id = "vpc-05948e9b0f8b42ce4"
}

import {
  to = aws_ebs_volume.vol-0569b7940f1b72e74
  id = "vol-0569b7940f1b72e74"
}

import {
  to = aws_ebs_volume.vol-09306925571e76dfe
  id = "vol-09306925571e76dfe"
}

import {
  to = aws_ebs_volume.vol-0dd1aa12b3fa086d2
  id = "vol-0dd1aa12b3fa086d2"
}

import {
  to = aws_ebs_volume.vol-0035f5d06012a0b93
  id = "vol-0035f5d06012a0b93"
}

import {
  to = aws_lb_target_group.web-target-group_fa33c1c324570f6f
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/web-target-group/fa33c1c324570f6f"
}

import {
  to = aws_iam_instance_profile.nat-instance_profile
  id = "nat-instance_profile"
}

import {
  to = aws_iam_instance_profile.web-server-asg_profile
  id = "web-server-asg_profile"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_lb.app_application-load-balancer_2b0ab14600dda1c1
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:loadbalancer/app/application-load-balancer/2b0ab14600dda1c1"
}

import {
  to = aws_kms_key.f019f965-2340-4c77-b976-182a1c3460ab
  id = "f019f965-2340-4c77-b976-182a1c3460ab"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_cloudwatch_log_group.aws_vpc_flowlogs_oregon-asg
  id = "/aws/vpc/flowlogs/oregon-asg"
}

import {
  to = aws_autoscaling_group.web-server-asg
  id = "web-server-asg"
}

import {
  to = aws_subnet.private-subnet-a
  id = "subnet-04f8936bbb980e2da"
}

import {
  to = aws_subnet.public-subnet-a
  id = "subnet-0fc79f8b9a5540bcf"
}

import {
  to = aws_subnet.public-subnet-c
  id = "subnet-0323b25f47f36503d"
}

import {
  to = aws_subnet.public-subnet-b
  id = "subnet-04161fb5562953ab3"
}

import {
  to = aws_subnet.private-subnet-b
  id = "subnet-0caa31b67692392d1"
}

import {
  to = aws_subnet.private-subnet-c
  id = "subnet-0113c2ad2bc2f618c"
}

import {
  to = aws_route_table_association.subnet-0323b25f47f36503d_rtb-0e7ef9f24d26b8594
  id = "subnet-0323b25f47f36503d/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table_association.subnet-0fc79f8b9a5540bcf_rtb-0e7ef9f24d26b8594
  id = "subnet-0fc79f8b9a5540bcf/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table_association.subnet-04161fb5562953ab3_rtb-0e7ef9f24d26b8594
  id = "subnet-04161fb5562953ab3/rtb-0e7ef9f24d26b8594"
}

import {
  to = aws_route_table_association.subnet-04f8936bbb980e2da_rtb-0c14faad417d3dac9
  id = "subnet-04f8936bbb980e2da/rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table_association.subnet-0113c2ad2bc2f618c_rtb-0c14faad417d3dac9
  id = "subnet-0113c2ad2bc2f618c/rtb-0c14faad417d3dac9"
}

import {
  to = aws_route_table_association.subnet-0caa31b67692392d1_rtb-0c14faad417d3dac9
  id = "subnet-0caa31b67692392d1/rtb-0c14faad417d3dac9"
}

import {
  to = aws_service_discovery_private_dns_namespace.alb-web-servers_namespace
  id = "vpc-05948e9b0f8b42ce4"
}
