# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

import {
  to = aws_egress_only_internet_gateway.eigw-083dc9b065af87635
  id = "eigw-083dc9b065af87635"
}

import {
  to = aws_vpc.oregon-asg-vpc2
  id = "vpc-0b2cb48f01ccce0c2"
}
