# Generated by Struct8 -- import targets for an account scan.
# Every block below points at a resource that ALREADY exists.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

import {
  to = aws_iam_policy.ecs_task_definition_hub_execution_st_loadtest-ecs-fargate
  id = "arn:aws:iam::952133486861:policy/ecs_task_definition_hub_execution_st_loadtest-ecs-fargate"
}

import {
  to = aws_iam_policy.ecs_task_definition_k6_execution_st_loadtest-ecs-fargate
  id = "arn:aws:iam::952133486861:policy/ecs_task_definition_k6_execution_st_loadtest-ecs-fargate"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-service_ltfargate-target_hub-AlarmHigh-1c10af14-a545-4c34-b7d7-6b9e7718597f
  id = "TargetTracking-service/ltfargate-target/hub-AlarmHigh-1c10af14-a545-4c34-b7d7-6b9e7718597f"
}

import {
  to = aws_cloudwatch_metric_alarm.TargetTracking-service_ltfargate-target_hub-AlarmLow-21727f27-d52e-40af-9b75-6311300c82c2
  id = "TargetTracking-service/ltfargate-target/hub-AlarmLow-21727f27-d52e-40af-9b75-6311300c82c2"
}

import {
  to = aws_instance.nat-a1
  id = "i-0bc1e9113c8ca6726"
}

import {
  to = aws_internet_gateway.ltfargate-igw
  id = "igw-0d302c5bcb04ebe6e"
}

import {
  to = aws_route_table.rt-private2
  id = "rtb-04a390cfd713d842d"
}

import {
  to = aws_route_table.rt-public2
  id = "rtb-046e608c912d4aa7a"
}

import {
  to = aws_security_group.sg-03f06085c9d641a04
  id = "sg-03f06085c9d641a04"
}

import {
  to = aws_security_group.ecs_task_definition_k6_group
  id = "sg-0200eb7dd60f773a3"
}

import {
  to = aws_security_group.ecs_task_definition_hub_group
  id = "sg-09c72c80334bf2d68"
}

import {
  to = aws_security_group.lb_alb-hub1_group
  id = "sg-05d485cb2ecda0082"
}

import {
  to = aws_subnet.public-k1
  id = "subnet-03c74003aef39aac0"
}

import {
  to = aws_subnet.public-alb-a
  id = "subnet-0e785f1db72891590"
}

import {
  to = aws_subnet.private-hub-a
  id = "subnet-0401f2bdea06ba269"
}

import {
  to = aws_subnet.public-alb-b
  id = "subnet-04ad197f470bdefa5"
}

import {
  to = aws_subnet.private-hub-b
  id = "subnet-0dc122e5e1db14b39"
}

import {
  to = aws_vpc.ltfargate-vpc
  id = "vpc-03c324cfff78416d5"
}

import {
  to = aws_ebs_volume.vol-0919e179df3910b1f
  id = "vol-0919e179df3910b1f"
}

import {
  to = aws_ecr_repository.struct8-hub
  id = "struct8-hub"
}

import {
  to = aws_ecs_cluster.ltfargate-target
  id = "ltfargate-target"
}

import {
  to = aws_ecs_cluster.ltfargate-tester
  id = "ltfargate-tester"
}

import {
  to = aws_ecs_service.k6_1
  id = "ltfargate-tester/k6"
}

import {
  to = aws_ecs_service.hub_1
  id = "ltfargate-target/hub"
}

import {
  to = aws_ecs_task_definition.hub
  id = "arn:aws:ecs:us-west-2:952133486861:task-definition/hub:5"
}

import {
  to = aws_ecs_task_definition.k6
  id = "arn:aws:ecs:us-west-2:952133486861:task-definition/k6:1"
}

import {
  to = aws_lb.alb-hub1
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:loadbalancer/app/alb-hub1/19535d4b0ce55c3e"
}

import {
  to = aws_lb_target_group.tg-hub1
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:targetgroup/tg-hub1/32291c4cf5291dff"
}

import {
  to = aws_iam_openid_connect_provider.token_actions_githubusercontent_com
  id = "arn:aws:iam::952133486861:oidc-provider/token.actions.githubusercontent.com"
}

import {
  to = aws_iam_role.execution_role_ecs_hub
  id = "execution_role_ecs_hub"
}

import {
  to = aws_iam_role.execution_role_ecs_k6
  id = "execution_role_ecs_k6"
}

import {
  to = aws_iam_instance_profile.nat-a1_profile
  id = "nat-a1_profile"
}

import {
  to = aws_iam_role.nat-a1_role
  id = "nat-a1_role"
}

import {
  to = aws_iam_role.Struct8-Gitops-Struct8-import
  id = "Struct8-Gitops-Struct8-import"
}

import {
  to = aws_iam_role.task_role_ecs_hub
  id = "task_role_ecs_hub"
}

import {
  to = aws_iam_role.task_role_ecs_k6
  id = "task_role_ecs_k6"
}

import {
  to = aws_cloudwatch_log_group.aws_ecs_containerinsights_ltfargate-tester_performance
  id = "/aws/ecs/containerinsights/ltfargate-tester/performance"
}

import {
  to = aws_cloudwatch_log_group.aws_lambda_us-east-1_Redirector
  id = "/aws/lambda/us-east-1.Redirector"
}

import {
  to = aws_cloudwatch_log_group.logs-target
  id = "/ecs/ltfargate-hub"
}

import {
  to = aws_cloudwatch_log_group.logs-tester
  id = "/ecs/ltfargate-k6"
}

import {
  to = aws_lb_listener.listener-http1
  id = "arn:aws:elasticloadbalancing:us-west-2:952133486861:listener/app/alb-hub1/19535d4b0ce55c3e/3dad19bc270f2612"
}

import {
  to = aws_appautoscaling_target.service_ltfargate-target_hub_ecs_service_DesiredCount_ecs
  id = "ecs/service/ltfargate-target/hub/ecs:service:DesiredCount"
}

import {
  to = aws_appautoscaling_policy.r_79bfc054-b894-4786-abd4-c2164a9e21c3_resource_ecs_service_ltfargate-target_hub_policyName_hub-scale-cpu_ecs_service_DesiredCount
  id = "ecs/service/ltfargate-target/hub/ecs:service:DesiredCount/hub-scale-cpu"
}

import {
  to = aws_route_table_association.subnet-0dc122e5e1db14b39_rtb-04a390cfd713d842d
  id = "subnet-0dc122e5e1db14b39/rtb-04a390cfd713d842d"
}

import {
  to = aws_route_table_association.subnet-0401f2bdea06ba269_rtb-04a390cfd713d842d
  id = "subnet-0401f2bdea06ba269/rtb-04a390cfd713d842d"
}

import {
  to = aws_route_table_association.subnet-04ad197f470bdefa5_rtb-046e608c912d4aa7a
  id = "subnet-04ad197f470bdefa5/rtb-046e608c912d4aa7a"
}

import {
  to = aws_route_table_association.subnet-03c74003aef39aac0_rtb-046e608c912d4aa7a
  id = "subnet-03c74003aef39aac0/rtb-046e608c912d4aa7a"
}

import {
  to = aws_route_table_association.subnet-0e785f1db72891590_rtb-046e608c912d4aa7a
  id = "subnet-0e785f1db72891590/rtb-046e608c912d4aa7a"
}

import {
  to = aws_service_discovery_private_dns_namespace.ltfargate-vpc_namespace
  id = "vpc-03c324cfff78416d5"
}
